name: Debug Symfony Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer

      - name: Show PHP version
        run: php -v

      - name: Show Composer version
        run: composer -V

      - name: Install dependencies (DEBUG)
        run: composer install -vvv

      - name: List files
        run: ls -la

      - name: FTP Deploy (only if previous success)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./
          server-dir: /public_html/greenloop-backend/
          dangerous-clean-slate: false